### PR TITLE
[ConfigTransformer] Fix xml import inlining

### LINKED ISSUE #178: [config-transformer] Add an option to disable import inlining
## The problem

Currently if you convert this kind of file with the config-transformer
```xml
<container>
    <import src="other.xml" />
</container>
```
it would be expected that the resulting php file would look like this
```php
<?php 
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->import('other.xml');
}
```
but instead it dumps the contents of the `other.xml` file into it.

## The suggestion
If I understand the code correctly in the command it basically lets the container parse the file and then gets the result of the parsed tree and dumps that into a file. This means this feature is not really possibile to implement other than with some preprocessing of the file before hand. (eg. removing the imports and then sending off the file to be read by the container).

### PR DESCRIPTION
**Pull request by TomasVotruba**
Closes #178

Resolves #179

### CODE REVIEW

File: packages/php-config-printer/src/YamlToPhpConverter.php [hunk 1]
```diff
@@ -55,27 +54,20 @@ final class YamlToPhpConverter
...
-    private $xmlImportCollector;
-
     public function __construct(
         Parser $yamlParser,
         PhpParserPhpConfigPrinter $phpParserPhpConfigPrinter,
         ContainerConfiguratorReturnClosureFactory $returnClosureNodesFactory,
         RoutingConfiguratorReturnClosureFactory $routingConfiguratorReturnClosureFactory,
         YamlFileContentProviderInterface $yamlFileContentProvider,
-        CheckerServiceParametersShifter $checkerServiceParametersShifter,
-        XmlImportCollector $xmlImportCollector
```
Comment (TomasVotruba) [inline packages/php-config-printer/src/YamlToPhpConverter.php]: @mamazu Hi, so everythign was correct. Just this is a different package `php-config-printer`, an "external dependency" for `config-transformer` package. Imagine it like a `vendor` dependency. It can be used, but it can't be written into.

The fix was to move the `XmlImportCollector` back to `config-transformer`

**Comment by TomasVotruba** [comment]
@mamazu Thank you for you work!
I've released new migrify version, so you can use it and test it in the wild :)

File: packages/php-config-printer/src/YamlToPhpConverter.php (hunk 1 above)
Comment (mamazu) [reply packages/php-config-printer/src/YamlToPhpConverter.php]: Ah okay good to know.

**Comment by mamazu** [comment]
Thanks I will try it out with some other project.
